---
# tasks file for ansible-cisco_iosxe_upgrade
#
# ██╗ ██████╗ ███████╗     ██╗  ██╗███████╗        ██████╗          ██████╗██╗     ███████╗ █████╗ ███╗   ██╗██╗███╗   ██╗ ██████╗ 
# ██║██╔═══██╗██╔════╝     ╚██╗██╔╝██╔════╝        ╚════██╗        ██╔════╝██║     ██╔════╝██╔══██╗████╗  ██║██║████╗  ██║██╔════╝ 
# ██║██║   ██║███████╗█████╗╚███╔╝ █████╗           █████╔╝        ██║     ██║     █████╗  ███████║██╔██╗ ██║██║██╔██╗ ██║██║  ███╗
# ██║██║   ██║╚════██║╚════╝██╔██╗ ██╔══╝          ██╔═══╝         ██║     ██║     ██╔══╝  ██╔══██║██║╚██╗██║██║██║╚██╗██║██║   ██║
# ██║╚██████╔╝███████║     ██╔╝ ██╗███████╗███████╗███████╗███████╗╚██████╗███████╗███████╗██║  ██║██║ ╚████║██║██║ ╚████║╚██████╔╝
# ╚═╝ ╚═════╝ ╚══════╝     ╚═╝  ╚═╝╚══════╝╚══════╝╚══════╝╚══════╝ ╚═════╝╚══════╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═══╝╚═╝╚═╝  ╚═══╝ ╚═════╝ 
#

- name: ios-xe_2_cleanup | Define section
  ansible.builtin.set_fact:
    section: "ios-xe_2_cleanup"

#   _           _        _ _ 
#  (_)_ __  ___| |_ __ _| | |
#  | | '_ \/ __| __/ _` | | |
#  | | | | \__ \ || (_| | | |
#  |_|_| |_|___/\__\__,_|_|_|
#                            
#------------------------------------------------------------------------------
# MODE INSTALL
#------------------------------------------------------------------------------
- name: ios-xe_2_cleanup | MODE INSTALL
  when:
    - device_install_mode is defined
    - device_install_mode|upper == "INSTALL"
  block:

    #   _           _        _ _ 
    #  (_)_ __  ___| |_ __ _| | |
    #  | | '_ \/ __| __/ _` | | |
    #  | | | | \__ \ || (_| | | |
    #  |_|_| |_|___/\__\__,_|_|_|
    #                            
    - name: "{{ section }} | MODE INSTALL | command 'install'"
      when: device_install_cmd|lower == "install"
      block:
    
        - name: "{{ section }} | MODE INSTALL | command 'install' | Running the software clean command"
          vars:
            ansible_command_timeout: 600
          register: command_results
          cisco.ios.ios_command:
            commands:
              - command: install remove inactive
                prompt: 'Do you want to remove the above files?'
                answer: 'y'
          
        - name: "{{ section }} | MODE INSTALL | command 'install' | Complete install remove"
          ansible.builtin.assert:
            that:
              - '{{ True if ("SUCCESS:" in command_results.stdout[0]) else False }}'
            msg: 'Running the software clean command failed.'
    
    
    #             __ _                          
    #  ___  ___  / _| |___      ____ _ _ __ ___ 
    # / __|/ _ \| |_| __\ \ /\ / / _` | '__/ _ \
    # \__ \ (_) |  _| |_ \ V  V / (_| | | |  __/
    # |___/\___/|_|  \__| \_/\_/ \__,_|_|  \___|
    #                                    
    - name: "{{ section }} | MODE INSTALL | command 'software'"
      when: device_install_cmd|lower == "software"
      block:

        - name: "{{ section }} | MODE INSTALL | command 'software' | Running the software clean command"
          vars:
            ansible_command_timeout: 600
          register: command_results
          cisco.ios.ios_command:
            commands:
              - command: software clean force

        - name: "{{ section }} | MODE INSTALL | command 'software' | Complete software remove"
          ansible.builtin.assert:
            that:
              - '{{ True 
                      if ( "Nothing to clean" in command_results.stdout[0] or
                           "Clean up completed" in command_results.stdout[0]
                      ) 
                      else False }}'
            msg: 'Running the software clean command failed.'

#------------------------------------------------------------------------------
# Define the next step
#------------------------------------------------------------------------------
- name: "{{ section }} | Next step"
  ansible.builtin.set_fact:
    ios_next_step: "staging"