---
# tasks file for ansible-cisco_iosxe_upgrade
#
# ██╗ ██████╗ ███████╗     ██╗  ██╗███████╗   ██╗  ██╗       ██╗   ██╗███████╗██████╗ ██╗███████╗██╗   ██╗██╗███╗   ██╗ ██████╗ 
# ██║██╔═══██╗██╔════╝     ╚██╗██╔╝██╔════╝   ██║  ██║       ██║   ██║██╔════╝██╔══██╗██║██╔════╝╚██╗ ██╔╝██║████╗  ██║██╔════╝ 
# ██║██║   ██║███████╗█████╗╚███╔╝ █████╗     ███████║       ██║   ██║█████╗  ██████╔╝██║█████╗   ╚████╔╝ ██║██╔██╗ ██║██║  ███╗
# ██║██║   ██║╚════██║╚════╝██╔██╗ ██╔══╝     ╚════██║       ╚██╗ ██╔╝██╔══╝  ██╔══██╗██║██╔══╝    ╚██╔╝  ██║██║╚██╗██║██║   ██║
# ██║╚██████╔╝███████║     ██╔╝ ██╗███████╗███████╗██║███████╗╚████╔╝ ███████╗██║  ██║██║██║        ██║   ██║██║ ╚████║╚██████╔╝
# ╚═╝ ╚═════╝ ╚══════╝     ╚═╝  ╚═╝╚══════╝╚══════╝╚═╝╚══════╝ ╚═══╝  ╚══════╝╚═╝  ╚═╝╚═╝╚═╝        ╚═╝   ╚═╝╚═╝  ╚═══╝ ╚═════╝ 
#

- name: ios-xe_4_verifying | Define section
  ansible.builtin.set_fact:
    section: "ios_4_verifying"

#------------------------------------------------------------------------------
# Image exist on device filesystem
#------------------------------------------------------------------------------
- name: "{{ section }} | IOS image found"
  ansible.builtin.assert:
    that:
      - found_required_file
    fail_msg: "The required IOS-XE image couldn't be found on device filesystem."
    success_msg: "The required IOS-XE image exist on device filesystem."

#------------------------------------------------------------------------------
# Required IOS image found on device filesystem
#------------------------------------------------------------------------------
- name:  "{{ section }}"
  when: found_required_file 
  block:

    #--------------------------------------------------------------------------
    # Validate if variable 'use_signature' is defined and set with the string
    # 'MD5' or 'SHA512'.
    #--------------------------------------------------------------------------
    - name: "{{ section }} | Validate use_signature"
      ansible.builtin.assert:
        that:
          - "use_signature|upper == 'MD5' or use_signature|upper == 'SHA512'"
          - "use_signature is defined"
        fail_msg: "The variable use_signature isn't defined or doesn't have the 
                  the string MD5 or SHA512."

    #--------------------------------------------------------------------------
    # Use command: verify /(<md5>|<sha512>) flash:<image name>
    #--------------------------------------------------------------------------
    - name: "{{ section }} | Compute an MD5 or SHA512 signature for a file"
      vars:
        ansible_command_timeout: 900
      register: hash_result
      cisco.ios.ios_command:
        commands: "verify 
          {{ 
            '/md5' 
              if (use_signature|upper == 'MD5') 
              else 
                ( 
                  '/sha512' 
                    if (use_signature|upper == 'SHA512') 
                    else '' 
                ) 
          }} {{ item }}{{ device_findfile_info[item]['filename'] }}"
      with_items: "{{ device_findfile_info.keys() | list }}"
    
    #--------------------------------------------------------------------------
    # If the string behind the variable 'required_ios_md5' or 
    # 'required_ios_sha512' matches with the output of the running command
    # verify then set the flag True into the list else False.
    #--------------------------------------------------------------------------
    - name: "{{ section }} | Validate checksum"
      set_fact:
        checksum_match: "{{ ( checksum_match|default([]) ) +  
            [ 
              (
                True
                  if (required_ios_md5 in item.stdout[0])
                  else False
              )
                if (use_signature|upper == 'MD5')
                else 
                (
                  True
                    if (required_ios_sha512 in item.stdout[0])
                    else False
                )
            ] }}"
      with_items: "{{ hash_result.results }}"

    #--------------------------------------------------------------------------
    # checksum_match = [ 'True' ]
    #--------------------------------------------------------------------------
    - name: "{{ section }} | Debug"
      when: debug
      ansible.builtin.debug: var=checksum_match

    #--------------------------------------------------------------------------
    # If the list contians the boolean False then to remove the IOS directory
    # on all member filesystems.
    #--------------------------------------------------------------------------
    - name: "{{ section }} | Verification failed on device - delete IOS image"
      when:
        - False in checksum_match
      cisco.ios.ios_command:
        commands: "delete /force /recursive {{ item }}{{ device_findfile_info[item]['filename'] }}"
      with_items: "{{ device_filesystem_info.keys() | list }}"
      
    - name: "{{ section }} | Validate when checksums are identical"
      ansible.builtin.assert:
        that: 
          - False not in checksum_match
        fail_msg: "Mismatch during validation of checksums"
        success_msg: "Checksum verification was successfully"

#------------------------------------------------------------------------------
# Define the next step
#------------------------------------------------------------------------------
- name: "{{ section }} | Next step"
  ansible.builtin.set_fact:
    ios_next_step: "installing"

#                       _ _   
#   _ __ ___  ___ _   _| | |_ 
#  | '__/ _ \/ __| | | | | __|
#  | | |  __/\__ \ |_| | | |_ 
#  |_|  \___||___/\__,_|_|\__|
#
#------------------------------------------------------------------------------
# Display result status
#------------------------------------------------------------------------------
- name: "{{ section }} | Results"
  ansible.builtin.debug:
    msg:
      - "{{
          (
            'Next step is ' + ios_next_step
          ) if
            (
              not using_tag
            ) 
          else 
            (
              (
                'Ending of tag verifying.'
              ) if 
                  (
                    ios_next_step|lower == 'verifying'
                  )
                else 
                  ( 
                    'Next step is ' + ios_next_step 
                  )
            )
        }}"
